---
- name: Set map fact
  ansible.builtin.set_fact:
    vm_map:
      helm:
        repository:
          url: '{{ vm_vars.kubernetes.helm.repository.url }}/{{ vm_vars.kubernetes.helm.repository.name }}'
        timeout: 5m0s
      