apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - targets/argocd.yaml
  - targets/calico.yaml
  - targets/kafka.yaml
  - dashboards/kafka-cluster.yaml
  - dashboards/kafka-topic.yaml
  - dashboards/kafka-consumer-group.yaml
  - dashboards/cert-manager.yaml
  - dashboards/postgres.yaml
