---
# Cert Manager
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cert-manager-to-world
  namespace: cert-manager
spec:
  endpointSelector: {}
  egress:
    # ACME challenge verification
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
