apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cert-manager-from-kube-apiserver-access
  namespace: cert-manager
spec:
  endpointSelector: {}
  ingress:
    # From Kubernetes API server (for webhook validation)
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
    # From Kubernetes API server
    - fromEndpoints:
        - matchLabels:
            component: apiserver
            io.kubernetes.pod.namespace: default
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
            - port: "443"
              protocol: TCP