apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vchen7629/Cyphria.git
    targetRevision: main
    path: infrastructure/kubernetes/roles/postgres/overlay

  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true