apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: cyphria-frontend=ghcr.io/vchen7629/cyphria-frontend:latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/cyphria-frontend.update-strategy: digest
spec: 
  project: default
  source:
    repoURL: https://github.com/Vchen7629/kubernetes-cluster.git
    targetRevision: main
    path: manifests/tenants/cyphria/frontend
    
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false