apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    chart: '{{ cloudflared_vars.kubernetes.helm.chart.name }}'
    repoURL: '{{ cloudflared_vars.kubernetes.helm.repository.url }}'
    targetRevision: '{{ cloudflared_vars.kubernetes.helm.chart.version }}'

    helm:
      valuesObject:
        metrics:
          enabled: {{ cloudflared_vars.kubernetes.metrics.enable }}
          port: '{{ cloudflared_vars.kubernetes.metrics.port }}'

        managed:
          enabled: false

        local:  
          enabled: true
          auth:
            tunnelID: "{{ tunnel_id }}"
            accountTag: "{{ account_tag }}"
            tunnelName: cyphria
            tunnelSecret: "{{ tunnel_secret }}"

          ingress:
            - hostname: '{{ cloudflared_vars.kubernetes.ingress.hostname }}'
              service: '{{ cilium_map.gateway.frontend.ingress }}'

            - hostname: '*.cyphria.com'
              service: '{{ cilium_map.gateway.frontend.ingress }}'
            
            - service: http_status:404
              
        resources:
          limits:
            memory: '{{ cloudflared_vars.kubernetes.resources.limits.memory }}'
          requests:
            cpu: '{{ cloudflared_vars.kubernetes.resources.requests.cpu }}'
            memory: '{{ cloudflared_vars.kubernetes.resources.requests.memory }}'
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true