k3s_vars:
  cluster:
    controlplane:
      tainted: true
    domain: cluster.local
    kubeconfig:
      local: true
      path: "{{ lookup('ansible.builtin.env', 'HOME') + '/.kube'}}"
    service:
      host: 127.0.0.1
      port: 6444
    tls_san: 
      - 10.0.0.167 # wlol in ip a
  network: 
    interface: wlo1
  release:
    kubepug:
      checksum: checksums.txt
      file: kubepug_linux_amd64.tar.gz
      name: kubepug
      repository:
        name: kubepug
        org: kubepug
      version: v1.7.1
  server:
    api:
      host: 10.0.0.167
      port: 6443
  service:
    debug: false
  