
- name: Create namespaces
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition: 
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ namespace }}"
  loop:
    - argocd
    - victoria-metrics
    - frontend
    - kafka
    - cloudflare-tunnel
    - external-dns
    - cert-manager
    - backend
    - postgres
  loop_control:
    loop_var: namespace