apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-repo-tls
  namespace: argocd
spec:
  secretName: argocd-repo-server-tls
  issuerRef:
    name: '{{ externaldns_project.cloudflare.cluster.issuer }}'
    kind: ClusterIssuer
  commonName: cyphria.com
  dnsNames:
    - cyphria.com
    - '*.cyphria.com'
  duration: 2160h  # 90 days
  renewBefore: 360h # 15 days