cloudflared_vars:
  kubernetes:
    helm:
      chart:
        name: cloudflared
        version: v1.7.3
      repository:
        url: https://charts.kubito.dev
    resources:
      limits:
        cpu: null
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 128Mi
    metrics:
      enable: true
      port: 20241
    ingress:
      hostname: cyphria.com
