- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - k3s
  loop_control:
    loop_var: role

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        timeout: 30
      any_errors_fatal: true
    
    - name: Ensure Postgres namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: postgres
        state: present

    - name: Ensure pgdata directory exists with correct permissions
      ansible.builtin.file:
        path: /mnt/8tb/pgdata
        state: directory
        owner: 70
        group: 70
        mode: '0700'
      become: true

    - name: Deploy PersistentVolume
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'persistant-volume.yaml') | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml

    - name: Deploy Operator
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'deploy_operator.yaml') | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
    
    - name: Deploy CRDS
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'deploy_crds.yaml') | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
    
