---
# Cloudflare Tunnel
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare-tunnel
spec:
  endpointSelector: {}
  ingress:
    # Allow traffic from the Internet
    - fromEntities:
        - world
    # Allow return traffic from Cilium Gateway
    - fromEndpoints:
        - matchLabels:
            k8s-app: cilium-envoy
            io.kubernetes.pod.namespace: kube-system
    # Prometheus metrics
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: victoria-metrics
      toPorts:
        - ports:
            - port: "20241"
              protocol: TCP
  egress:
    # DNS lookups
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
    # Allow all other egress (required for L7 visibility with LoadBalancer)
    - toEntities:
        - all