---
# Nginx Ingress Controller
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  endpointSelector: {}
  ingress:
    # Prometheus metrics scraping
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: victoria-metrics
      toPorts:
        - ports:
            - port: "10254"
              protocol: TCP
    # Traffic from cloudflare tunnel
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cloudflare-tunnel
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
    # Traffic from svclb (klipper load balancer) pods
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            svccontroller.k3s.cattle.io/svcnamespace: nginx
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
  egress:
    # Kubernetes API access
    - toEntities:
      - kube-apiserver
    - toEntities:
      - host
    # DNS lookups (UDP)
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    # DNS lookups (TCP)
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
    # nginx -> frontend
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: frontend
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
    # nginx -> loginapi
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loginapi
            io.kubernetes.pod.namespace: backend
        - matchLabels:
            argocd.argoproj.io/instance: login-api
            io.kubernetes.pod.namespace: backend
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
