apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-dns-to-kube-apiserver-access
  namespace: external-dns
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: external-dns
  egress:
    # Kubernetes API access
    - toEntities:
      - kube-apiserver