apiVersion: v1
kind: PersistentVolume
metadata:
  name: hard-drive-pv
spec:
  capacity:
    storage: 7Ti
  accessModes:
    - ReadWriteOnce # For use on the same node
  persistentVolumeReclaimPolicy: Retain # data is not deleted with pvc
  storageClassName: local-storage
  local:
    path: /mnt/8tb/pgdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - tiamat-rog-strix-g15ce-g15ce