apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vchen7629/kubernetes-cluster.git
    targetRevision: main
    path: manifests/observability/victoria_metrics

  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true