# Topic containing the topics classified of
# the post corresponding to the post id
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-classified
  namespace: kafka
  labels:
    # cluster name that the topics are in
    strimzi.io/cluster: cyphria-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 28800000 # 8 hours
    segment.bytes: 1073741824