- name: Validate Role
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  block:
    - name: install k3s binary
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3-installer.sh
        owner: root
        group: root
        mode: '755'
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: execute binary
      ansible.builtin.shell: sh /tmp/k3-installer.sh
      args: 
        chdir: /tmp/
      register: binary
      retries: 3
      delay: 1
      until: binary is not failed
    
    - name: Create configuration directory
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory
        owner: root
        group: root
        mode: '755'

    - name: Set role postinstall fact
      ansible.builtin.set_fact:
        k3s_postinstall: false

    - name: Create configuration file
      ansible.builtin.template:
        src: config.j2
        dest: '{{ k3s_project.cluster.config }}'
        owner: root
        group: root
        mode: '600'

    - name: Create kubelet configuration file
      ansible.builtin.template:
        src: config_kubelet.j2
        dest: '{{ k3s_project.cluster.config_kubelet }}'
        owner: root
        group: root
        mode: '644'

    - name: Create service file
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/{{ k3s_map.service.name }}.service
        owner: root
        group: root
        mode: '644'

    - name: Create service environment file
      ansible.builtin.file:
        path: /etc/systemd/system/{{ k3s_map.service.name }}.service.env
        access_time: preserve
        modification_time: preserve
        state: touch
        owner: root
        group: root
        mode: '600'
    
    - name: Enable and start k3s-agent
      when: inventory_hostname in k3s_map.agent.hosts
      ansible.builtin.systemd:
        name: k3s-agent
        enabled: yes
        state: started
      become: true
      

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: role configuration
  ansible.builtin.import_tasks:
    file: configuration.yaml

- name: Server configuration
  notify: Restart service
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: finish role postinitialization
      ansible.builtin.set_fact:
        k3s_postinstall: true
      
    - name: set server config file
      ansible.builtin.template:
        src: config.j2
        dest: /etc/rancher/k3s/config.yaml
        owner: root
        group: root
        mode: '600'
      
      
  