apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # network policies (egress)
  - network-policy/egress-to-bootstrap.yaml
  - network-policy/egress-to-data.yaml
  - network-policy/egress-to-grafana.yaml
  - network-policy/egress-to-host.yaml
  - network-policy/egress-to-kube-apiserver.yaml
  - network-policy/egress-to-kube-dns.yaml
  - network-policy/egress-to-kube-system.yaml
  - network-policy/egress-to-messaging.yaml
  - network-policy/egress-to-networking.yaml
  - network-policy/egress-to-platform.yaml
  - network-policy/egress-to-remote-node.yaml
  - network-policy/egress-to-vm.yaml

  # network policies (ingress)
  - network-policy/ingress-from-grafana.yaml
  - network-policy/ingress-from-health-check.yaml
  - network-policy/ingress-from-host.yaml
  - network-policy/ingress-from-kubelet.yaml
  - network-policy/ingress-from-vm-agent.yaml
  - network-policy/ingress-from-vm-stack.yaml
