
- name: OS configuration
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - cluster
  tags: cluster

#- name: Provision Load Balancer
#  hosts: cluster
#  become: true
#  gather_facts: true

- name: k3s Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles: 
    - k3s
    - helm
  serial:
    - 1
    - 2
    - 5
  tags: kubernetes

- name: ArgoCD deployed applications provisioning
  hosts: server
  become: true
  gather_facts: true
  post_tasks:
    - name: Perform post-install tasks
      ansible.builtin.include_role:
        name: '{{ postinstall }}'
        tasks_from: postinstall
      loop:
        - argo_cd
        - metrics_server
        - cilium
      loop_control:
        loop_var: postinstall
  roles: 
    - cilium
    - argo_cd
    - network_policies
    - metrics_server
    - prometheus
    - cert_manager
    - nginx
    - kafka
    - cloudflare_tunnel
    - external_dns
    - frontend
  tags: charts