- name: Reset Cluster
  hosts: server
  become: true
  serial:
    - 3
    - 5
  tasks:
  - name: Reset cluster
    ansible.builtin.include_role:
      apply:
        tags: '{{ reset }}'
      name: '{{ reset }}'
      tasks_from: reset
    loop:
      #- network_policies
      #- cert_manager
      #- prometheus
      #- victoria_metrics
      #- nginx
      - kafka
      #- cloudflare_tunnel
      #- external_dns
      #- frontend
      #- postgres
      #- argo_cd
      #- cilium
    loop_control:
      loop_var: reset
      