apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyphria-frontend-deployment
  labels:
    app.kubernetes.io/name: cyphria-frontend
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: cyphria-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cyphria-frontend
    spec:
      containers:
        - name: cyphria-frontend
          image: ghcr.io/vchen7629/cyphria-frontend
          resources:
            limits:
              memory: 128Mi
            requests: 
              cpu: 100m
              memory: 64Mi
