apiVersion: v1
kind: Service
metadata:
  name: cyphria-frontend-service
spec: 
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: cyphria-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
