# Kafka Broker Network Policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kafka-broker-from-operator-access
  namespace: kafka
spec:
  endpointSelector:
    matchLabels:
      strimzi.io/cluster: cyphria-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: cyphria-cluster-kafka
  ingress:
    # Allow Strimzi Cluster Operator
    - fromEndpoints:
        - matchLabels:
            strimzi.io/kind: cluster-operator
            io.kubernetes.pod.namespace: kafka
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
            - port: "9090"
              protocol: TCP
            - port: "9091"
              protocol: TCP