- name: Configure namespaces
  ansible.builtin.import_tasks:
    file: namespaces.yaml
  any_errors_fatal: true


- name: Configure Network Policies
  block:
    - name: Apply Namespace-Scoped Cilium Network Policies
      ansible.builtin.shell:
        cmd: "kubectl apply -f -"
        stdin: "{{ lookup('file', item) }}"
      with_items:
        - "{{ role_path }}/templates/argocd.yaml"
        - "{{ role_path }}/templates/kafka-namespace.yaml"
        - "{{ role_path }}/templates/victoria-metrics-namespace.yaml"
        - "{{ role_path }}/templates/frontend-namespace.yaml"
        - "{{ role_path }}/templates/cloudflare-tunnel-namespace.yaml"
        - "{{ role_path }}/templates/external-dns-namespace.yaml"
        - "{{ role_path }}/templates/cert-manager-namespace.yaml"
        #- "{{ role_path }}/templates/backend-namespace.yaml"
        - "{{ role_path }}/templates/postgres-namespace.yaml"
      register: result
      retries: 3
      delay: 1
      until: result is not failed
    
    
          

        