- name: Deleting Network Policies
  block:
    - name: Delete all Cilium Network Policies by namespace
      ansible.builtin.shell:
        cmd: kubectl delete ciliumnetworkpolicy --all -n {{ item }}
      with_items:
        - argocd
        - victoria-metrics
        - frontend
        - kafka
        - cloudflare-tunnel
        - external-dns
        - cert-manager
        - postgres
        - kube-system
        - backend
      ignore_errors: true
