apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: frontend-to-argocd-repo-server-access
  namespace: cinesense-frontend
spec:
  endpointSelector: {}
  egress:
    # frontend -> ArgoCD Repo Server
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argocd-repo-server
            io.kubernetes.pod.namespace: argocd
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP