apiVersion: v1
kind: Service
metadata:
  name: cinesense-frontend-service
spec: 
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: cinesense-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
