apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-dns-to-host-access
  namespace: external-dns
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: external-dns
  egress:
    - toEntities:
      - host