

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  post_tasks:
    - name: Perform post-install tasks
      ansible.builtin.include_role:
        name: '{{ postinstall }}'
        tasks_from: postinstall
      loop:
        - cilium
        - argo_cd
      loop_control:
        loop_var: postinstall
  roles:
    - cilium
    - cert_manager
    - cloudflare_tunnel
    - external_dns
    - frontend
  tags: charts