- name: Reset Cluster
  hosts: server
  become: true
  serial:
    - 3
    - 5
  tasks:
  - name: Get packages information
    ansible.builtin.package_facts:

  - name: Reset cluster
    ansible.builtin.include_role:
      apply:
        tags: '{{ reset }}'
      name: '{{ reset }}'
      tasks_from: reset
    loop:
      - platform/cert_manager
      - observability/victoria_metrics
      - networking/nginx
      - messaging/kafka
      - networking/cloudflare_tunnel
      - networking/external_dns
      - tenants/cyphria/frontend
      - data/postgres
      - bootstrap/argocd
      - networking/cilium
      - bootstrap/helm
      - bootstrap/k3s
      - bootstrap/cluster
    loop_control:
      loop_var: reset
      