- name: Cluster Upgrade
  hosts: server
  become: true
  gather_facts: true
  tasks:
    - name: Role Upgrade
      ansible.builtin.include_role:
        apply:
          tags: '{{ upgrade }}'
        name: '{{ upgrade }}'
        tasks_from: upgrade
      loop: 
        #- cilium
        - network_policies
        #- kafka
        #- external_dns
        #- cloudflare_tunnel
        #- frontend
      loop_control:
        loop_var: upgrade