apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # docker image target for deployment onto the cluster
  - application/deployment.yaml
  - application/service.yaml
  - application/autoscaler.yaml

  # network policies (egress)
  - network-policy/egress-to-argocd-repo-server.yaml
  - network-policy/egress-to-argocd-kubedns.yaml

images:
  - name: ghcr.io/vchen7629/cyphria-frontend
    newTag: latest