apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cloudflare-tunnel-to-envoy
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: cilium-envoy
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cloudflare-tunnel